/**
 * Wellness Agents — Specialized Agent Definitions & Pipeline Runners
 *
 * Defines all 4 specialized agents in the multi-agent system and exports
 * pipeline runner functions that compose them together.
 *
 * Agent Pipeline:
 * 1. checkinAgent    → Conducts empathetic multi-turn wellness check-in
 * 2. extractionAgent → Extracts structured JSON from the conversation transcript
 * 3. patternAgent    → Analyzes check-in history for mood trends and insights
 * 4. nudgeAgent      → Generates personalized, actionable wellness nudges
 *
 * @module agents/wellness-agents
 */

import { BaseAgent, type ConversationTurn } from "./base-agent";
import {
  getRecentCheckIns,
  savePattern,
  saveNudge,
} from "./memory-agent";

// ---------------------------------------------------------------------------
// Extracted Data Types
// ---------------------------------------------------------------------------

/** Structured data extracted from a check-in conversation. */
export interface ExtractedCheckIn {
  moodScore: number;
  energy: number;
  sleep: number | null;
  summary: string;
  worries: string | null;
  tags: string[];
}

/** A single nudge generated by the nudge agent. */
export interface NudgeItem {
  message: string;
  category: "sleep" | "exercise" | "social" | "work" | "mindfulness";
}

/** Pattern analysis output from the pattern agent. */
interface PatternAnalysis {
  moodTrend: "improving" | "declining" | "stable" | "volatile";
  summary: string;
  insights: {
    triggers: string[];
    boosters: string[];
    correlations: string[];
    highlights: string[];
  };
}

/** Nudge agent output. */
interface NudgeOutput {
  nudges: NudgeItem[];
}

// ---------------------------------------------------------------------------
// Agent 1: Check-In Agent
// Conducts warm, empathetic daily wellness conversations across 2-3 turns.
// Asks about mood, energy, worries, and optionally sleep.
// Signals completion by appending [CHECK-IN COMPLETE] to its final reply.
// ---------------------------------------------------------------------------

const checkinAgent = new BaseAgent({
  name: "wellness_checkin_agent",
  description:
    "Conducts warm, empathetic daily wellness check-in conversations",
  temperature: 0.7,
  instructions: `You are a warm, empathetic daily wellness companion. Your job is to conduct a natural check-in conversation across 2-3 turns.

During the conversation, gather the following information naturally:
- Mood on a scale of 1-10
- Energy level on a scale of 1-10
- What happened today / how their day is going
- Any worries or concerns
- Optionally, how they slept last night

Be conversational and caring — don't make it feel like a form. Ask follow-up questions based on what the user shares. Show genuine interest.

When you have gathered enough information (at minimum mood, energy, and a sense of how their day is going), wrap up with a brief, supportive closing message and append exactly this marker on its own line at the very end:
[CHECK-IN COMPLETE]

Do NOT include the marker until you have enough information for a meaningful check-in.`,
});

// ---------------------------------------------------------------------------
// Agent 2: Extraction Agent
// Parses raw conversation transcripts into structured JSON.
// Zero creativity (temperature 0.1) — pure data extraction.
// ---------------------------------------------------------------------------

const extractionAgent = new BaseAgent({
  name: "wellness_extraction_agent",
  description:
    "Extracts structured wellness data from check-in conversation transcripts",
  temperature: 0.1,
  jsonMode: true,
  instructions: `You are a precise data extraction agent. Given a check-in conversation transcript, extract structured wellness data.

Output ONLY this exact JSON shape — no extra keys, no markdown, no explanation:
{
  "moodScore": number (1-10, based on what the user expressed),
  "energy": number (1-10, based on what the user expressed),
  "sleep": number | null (hours of sleep if mentioned, null otherwise),
  "summary": string (1-2 sentence summary of how the user is doing),
  "worries": string | null (main worries if mentioned, null otherwise),
  "tags": string[] (2-4 tags from: work, social, health, sleep, exercise, family, finance, other)
}

If the user didn't explicitly give a number for mood or energy, infer from the context and sentiment. Be accurate and conservative.`,
});

// ---------------------------------------------------------------------------
// Agent 3: Pattern Agent
// Analyzes historical check-in data to identify mood trends and insights.
// Low creativity (temperature 0.2) for consistent, reliable analysis.
// ---------------------------------------------------------------------------

const patternAgent = new BaseAgent({
  name: "wellness_pattern_agent",
  description:
    "Analyzes check-in history to identify mood patterns, triggers, and trends",
  temperature: 0.2,
  jsonMode: true,
  instructions: `You are a wellness pattern analysis agent. Given a series of check-in entries, analyze the data to identify mood trends, triggers, and insights.

Return ONLY this exact JSON shape — no extra keys, no markdown, no explanation:
{
  "moodTrend": "improving" | "declining" | "stable" | "volatile",
  "summary": string (2-3 warm, insightful sentences about the user's patterns),
  "insights": {
    "triggers": string[] (things that seem to worsen mood/energy),
    "boosters": string[] (things that seem to improve mood/energy),
    "correlations": string[] (patterns noticed, e.g. "sleep under 6h correlates with lower mood"),
    "highlights": string[] (positive moments or achievements)
  }
}

Be warm and non-judgmental in the summary. Focus on actionable insights.`,
});

// ---------------------------------------------------------------------------
// Agent 4: Nudge Agent
// Generates personalized, specific wellness nudges tied to the user's own data.
// Medium creativity (temperature 0.5) for engaging but relevant suggestions.
// ---------------------------------------------------------------------------

const nudgeAgent = new BaseAgent({
  name: "wellness_nudge_agent",
  description:
    "Generates personalized wellness nudges based on patterns and recent data",
  temperature: 0.5,
  jsonMode: true,
  instructions: `You are a personalized wellness nudge agent. Based on the user's mood patterns and recent check-in data, generate 1-2 specific, actionable nudges.

Rules:
- Never give generic advice like "drink more water" or "go for a walk"
- Tie every nudge to something specific from the user's own data
- Each nudge should be completable in under 30 minutes
- Be warm, encouraging, and specific

Return ONLY this exact JSON shape — no extra keys, no markdown, no explanation:
{
  "nudges": [
    {
      "message": string (the personalized nudge, 1-2 sentences),
      "category": "sleep" | "exercise" | "social" | "work" | "mindfulness"
    }
  ]
}`,
});

// ---------------------------------------------------------------------------
// Pipeline Runners
// ---------------------------------------------------------------------------

/**
 * Run a single turn of the check-in conversation.
 * Strips the [CHECK-IN COMPLETE] marker from the reply if present.
 *
 * @param history     - Prior conversation turns
 * @param userMessage - The latest user message
 * @returns Object with the agent's reply and whether the check-in is complete
 */
export async function runCheckinTurn(
  history: ConversationTurn[],
  userMessage: string
): Promise<{ reply: string; isComplete: boolean }> {
  const result = await checkinAgent.run(userMessage, history);
  const isComplete = result.isComplete;
  const reply = result.text.replace("[CHECK-IN COMPLETE]", "").trim();

  return { reply, isComplete };
}

/**
 * Extract structured wellness data from a completed check-in conversation.
 * Builds a transcript string from the conversation history and sends it
 * to the extraction agent for JSON parsing.
 *
 * @param conversation - Full conversation transcript as string
 * @returns Extracted check-in data (without rawText)
 */
export async function extractCheckinData(
  conversation: string
): Promise<ExtractedCheckIn> {
  return extractionAgent.runJSON<ExtractedCheckIn>(
    `Extract wellness data from this check-in conversation:\n\n${conversation}`
  );
}

/**
 * Run the pattern analysis and nudge generation pipeline.
 *
 * Steps:
 * 1. Fetch recent check-ins (14 days) from the memory agent
 * 2. Run the pattern agent to analyze trends
 * 3. Save the pattern to the database
 * 4. Run the nudge agent with pattern context
 * 5. Save generated nudges to the database
 *
 * @param userId           - The user to analyze
 * @param currentMoodScore - The mood score from the just-completed check-in
 * @returns Object containing the generated nudges
 */
export async function runPatternAndNudgePipeline(
  userId: string,
  currentMoodScore: number
): Promise<{ nudges: NudgeItem[] }> {
  // Step 1: Get recent check-ins
  const recentCheckIns = await getRecentCheckIns(userId, 14);

  if (recentCheckIns.length === 0) {
    return { nudges: [] };
  }

  // Build a summary of check-ins for the pattern agent
  const checkInSummary = recentCheckIns
    .map(
      (ci) =>
        `Date: ${ci.createdAt.toISOString().split("T")[0]}, Mood: ${ci.moodScore}/10, Energy: ${ci.energy}/10, Sleep: ${ci.sleep ?? "N/A"}h, Summary: ${ci.summary}, Tags: ${ci.tags.join(", ")}`
    )
    .join("\n");

  // Step 2: Run pattern analysis
  const patternResult = await patternAgent.runJSON<PatternAnalysis>(
    `Analyze these ${recentCheckIns.length} check-ins for patterns:\n\n${checkInSummary}\n\nCurrent mood today: ${currentMoodScore}/10`
  );

  // Step 3: Save the pattern
  const weekStart = new Date();
  weekStart.setDate(weekStart.getDate() - weekStart.getDay());
  weekStart.setHours(0, 0, 0, 0);

  const savedPattern = await savePattern(userId, weekStart, {
    moodTrend: patternResult.moodTrend,
    summary: patternResult.summary,
    insights: patternResult.insights as unknown as import("@prisma/client").Prisma.InputJsonValue,
    entryCount: recentCheckIns.length,
  });

  // Step 4: Run nudge generation
  const nudgeResult = await nudgeAgent.runJSON<NudgeOutput>(
    `Based on this pattern analysis, generate personalized nudges:\n\nMood Trend: ${patternResult.moodTrend}\nSummary: ${patternResult.summary}\nTriggers: ${patternResult.insights.triggers.join(", ")}\nBoosters: ${patternResult.insights.boosters.join(", ")}\nCorrelations: ${patternResult.insights.correlations.join(", ")}\nCurrent mood: ${currentMoodScore}/10\n\nRecent check-in data:\n${checkInSummary}`
  );

  // Step 5: Save each nudge
  for (const nudge of nudgeResult.nudges) {
    await saveNudge(userId, nudge.message, nudge.category, savedPattern.id);
  }

  return { nudges: nudgeResult.nudges };
}
